apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-service-broker-auth
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
type: Opaque
stringData:
  username: {{ .Values.atlas.publicApiKey }}@{{ .Values.atlas.projectId }}
  password: {{ .Values.atlas.privateApiKey }}
