apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Release.Name }}-tardigrade-gateway
data: 
  config.yaml: |
    api-key: {{ .Values.api_key }}
    satellite-addr: us-central-1.tardigrade.io 
    access: {{ .Values.access }} 
    minio.access-key: {{ .Values.accessKey }} 
    minio.secret-key: {{ .Values.secretKey }}
    server.address: :7777
    client.user-agent: MongoDB
