kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-tardigrade-gateway
stringData:
  accessKey: {{ .Values.accessKey }} 
  secretKey: {{ .Values.secretKey }}

