apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-k8s-ui
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: {{ .Release.Name }}-mongodb-k8s-ui
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-k8s-ui
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb-k8s-ui
    spec:
      containers:
      - name: mongodb-k8s-ui 
        image: jmimick/mongodb-k8s-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
