---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}


---
kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRole {{ else }} Role {{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
  {{- if not (eq (.Values.operator.watchNamespace | default "*") "*") }}
  namespace: {{ .Values.operator.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    product: {{ .Chart.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  {{- if eq (.Values.operator.watchNamespace | default "") "*" }}
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
  {{- end}}
- apiGroups:
  - mongodb.com
  resources:
  - mongodb
  - mongodb/finalizers
  - mongodbusers
  - opsmanagers
  - opsmanagers/finalizers
{{- if .Values.subresourceEnabled }}
  - mongodb/status
  - mongodbusers/status
  - opsmanagers/status
{{- end }}
  verbs:
  - "*"
# This ClusterRoleBinding is necessary in order to use validating
# webhooks—these will prevent you from applying a variety of invalid resource
# definitions. The validating webhooks are optional so this can be removed if
# necessary.
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Release.Namespace }}-webhook-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-enterprise-operator-mongodb-webhook
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}

---
kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRoleBinding {{ else }} RoleBinding {{ end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}
  {{- if not (eq (.Values.operator.watchNamespace | default "*") "*") }}
  namespace: {{ .Values.operator.watchNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    product: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if eq (.Values.operator.watchNamespace | default "") "*" }} ClusterRole {{ else }} Role {{ end }}
  name: {{ .Values.operator.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}

# This ClusterRole is needed if the user wants to use the Kubernetes CA
# infrastructure to generate certificates.
{{- if .Values.needsCAInfrastructure }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Release.Namespace }}-certs
  labels:
    product: {{ .Chart.Name }}
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - create
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ .Release.Namespace }}-certs-binding
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.name }}-{{ .Release.Namespace }}-certs
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
