{{- if .Values.opsManager }}
---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: {{ .Release.Name }}-ops-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-ops-manager
    product: {{ .Chart.Name }}
spec:
  replicas: 1 
  version: 4.2.4
  adminCredentials: {{ .Release.Name }}-ops-manager-secret
  externalConnectivity:
    type: LoadBalancer
  podSpec:
    podTemplate:
      spec:
        # This container will be added to each pod as a sidecar
        containers:
          - name: smtp-sidecar
            image: bytemark/smtp
          - name: {{ .Release.Name }}-ops-manager
            env:
            - name: SKIP_OPS_MANAGER_REGISTRATION
              value: "true"
{{- if .Values.opsManager.nodeAffinity }}
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/role 
              operator: In
              values:
              - {{ .Values.opsManager.nodeAffinity.nodeRole }}
{{- end }}

{{- with .Values.opsManager.backup }}
  backup:
    {{- toYaml . | nindent 4 }}
{{- end }}
    opLogStores:
    - name: oplog1
      mongodbResourceRef:
        name: {{ .Release.Name }}-ops-manager-backup 

#{{ .Values.opsManager.nodeAffinity }}
{{- if .Values.opsManager.nodeAffinity }}
    podSpec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role 
                operator: In
                values:
                - {{ .Values.opsManager.nodeAffinity.nodeRole }}-backup-daemon
{{- end }}

  # the Ops Manager configuration. All the values must be of type string
  configuration:
    mms.fromEmailAddr: {{ .Values.mail.relayUsername }}
    mms.replyToEmailAddr: {{ .Values.mail.relayUsername }}
    mms.adminEmailAddr: {{ .Values.mail.relayUsername }}
    mms.mail.transport: "smtp"
    mms.mail.hostname: {{ .Release.Name }}-mail
    mms.mail.port: "25"
    mms.ignoreInitialUiSetup: "true"

  applicationDatabase:
    members: 3
    version: 4.2.0
    persistent: true
{{- if .Values.opsManager.nodeAffinity }}
    podSpec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role 
                operator: In
                values:
                - {{ .Values.opsManager.nodeAffinity.nodeRole }}
{{- end }}
{{- end }}

