  
name: CI

on:
  push:
    paths:
    - '**'
    - '!kurl-installer.yaml'
    - '!**.md'
    - '!doc/**'
    - '!**.png'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Create a release on Channel associated with the branch
      run: |
        make -C kots release channel=${GITHUB_REF#refs/heads/} release_notes="'GitHub Action release of ${GITHUB_REF} triggered by ${GITHUB_ACTOR}: [${GITHUB_SHA::7}](https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})'"
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
